use_frameworks!

platform :ios, '9.0'

target 'YojoComplexListView_Example' do
  pod 'YojoComplexListView', :path => '../'

  target 'YojoComplexListView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
